spring:
  application:
    name: blog-application
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/cs544?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: false
logging:
  level:
    root: warn
server:
  port:8080
#  port:8081 Post
#  port:8082 Comment
#  port:8083 User

